### ISSUE TITLE
ValueError: optimizer got an empty parameter list

### ISSUE THREAD

**Issue by Max-luo-song** [water-splatting/water-splatting#1]
Hello, I am trying to run your work. But I meet some problems. I hope to get help here. This is my error log：

Traceback (most recent call last):
  File "/data/gls/miniconda3/envs/water_splatting/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/data/gls/miniconda3/envs/water_splatting/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/data/gls/miniconda3/envs/water_splatting/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/data/gls/miniconda3/envs/water_splatting/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/data/gls/miniconda3/envs/water_splatting/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/data/gls/miniconda3/envs/water_splatting/lib/python3.8/site-packages/nerfstudio/engine/trainer.py", line 161, in setup
    self.optimizers = self.setup_optimizers()
  File "/data/gls/miniconda3/envs/water_splatting/lib/python3.8/site-packages/nerfstudio/engine/trainer.py", line 227, in setup_optimizers
    return Optimizers(optimizer_config, param_groups)
  File "/data/gls/miniconda3/envs/water_splatting/lib/python3.8/site-packages/nerfstudio/engine/optimizers.py", line 108, in __init__
    self.optimizers[param_group_name] = config[param_group_name]["optimizer"].setup(params=params)
  File "/data/gls/miniconda3/envs/water_splatting/lib/python3.8/site-packages/nerfstudio/engine/optimizers.py", line 53, in setup
    return self._target(params, **kwargs)
  File "/data/gls/miniconda3/envs/water_splatting/lib/python3.8/site-packages/torch/optim/adam.py", line 45, in __init__
    super().__init__(params, defaults)
  File "/data/gls/miniconda3/envs/water_splatting/lib/python3.8/site-packages/torch/optim/optimizer.py", line 261, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list

The input is：ns-train water-splatting --vis viewer+wandb colmap --downscale-factor 1 --colmap-path /data/gls/water-splatting-main/dataset/SeathruNeRF_dataset/SeathruNeRF_dataset/IUI3-RedSea/sparse/0 --data /data/gls/water-splatting-main/dataset/SeathruNeRF_dataset/SeathruNeRF_dataset/IUI3-RedSea --images-path images_wb

The only different point with your defalut settings is that the cuda version of my mechine is CUDA-12.1， so I install the torch 2.1.2+cu121 and torchvision 0.16.2+cu121, is this matter or other solutions?

Thanks！

**Comment by Max-luo-song** [comment]
I reset the environment according to the instructions and it works now. 
According to my situation, CUDA 12.1 is available
